### ISSUE TITLE
Can PR status be updated via autolinked references?

### ISSUE THREAD

**Issue by dzhoshkun** [pymor/ci_hooks_app#1]
[GitHub allows for PRs to be referenced e.g. in commit messages](https://help.github.com/articles/autolinked-references-and-urls/#issues-and-pull-requests)

Can this be combined with GitLab CI/CD for GitHub to eliminate the need for installing the functionality as a separate GitHub app?

**Comment by renefritze** [comment]
The GitHub app installation makes it possible to set a status for a commit. I don't see how that relates to these shortened references.
